name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.1

      - name: Install dependencies
        run: go mod tidy

      # - name: Run tests
      #   run: go test ./... -coverprofile=coverage.out

      # - name: Display coverage
      #   run: go tool cover -func=coverage.out

      name: Go CI/CD


# TO DEPLOY TO CLOUD
# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Go
#       uses: actions/setup-go@v4
#       with:
#         go-version: 1.20

#     - name: Install dependencies
#       run: go mod tidy

#     - name: Run tests
#       run: go test ./... -coverprofile=coverage.out

#     - name: Display coverage
#       run: go tool cover -func=coverage.out
